name: Moodle Plugin CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Moodle Plugin CI - ${{ matrix.moodle-branch }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        moodle-branch: ['MOODLE_403_STABLE', 'MOODLE_400_STABLE', 'MOODLE_500_STABLE']

    steps:
      - name: Checkout plugin code
        uses: actions/checkout@v3

      - name: Setup Moodle Plugin CI
        uses: moodlehq/moodle-plugin-ci@v3
        with:
          moodle-branch: ${{ matrix.moodle-branch }}

      - name: Run plugin CI checks
        run: |
          moodle-plugin-ci lint
          moodle-plugin-ci validate
          moodle-plugin-ci codechecker
          moodle-plugin-ci phpdoc
          moodle-plugin-ci phpunit

      - name: Upload Codechecker Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: codechecker-report-${{ matrix.moodle-branch }}
          path: codechecker_after.json
