name: Moodle Plugin CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['8.2']
        moodle-branch: ['MOODLE_404_STABLE']
        db: ['pgsql']

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres   # <— WICHTIG: NICHT 'moodle'
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, zip, gd, pgsql
          coverage: none

      - name: Install moodle-plugin-ci
        run: |
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci:"^4.0" ~/.moodle-plugin-ci
          echo "$HOME/.moodle-plugin-ci/bin" >> $GITHUB_PATH

      # optional, aber macht den Install-Schritt idempotent
      - name: Reset Postgres database (idempotent)
        run: |
          PGPASSWORD=postgres psql -U postgres -h 127.0.0.1 -d postgres -c 'DROP DATABASE IF EXISTS "moodle";'

      - name: Install Moodle + plugin under test
        run: |
          moodle-plugin-ci install -vvv \
            --branch=${{ matrix.moodle-branch }} \
            --db-type=pgsql \
            --db-host=127.0.0.1 \
            --db-user=postgres \
            --db-pass=postgres \
            --db-name=moodle

      - name: PHP Lint
        run: moodle-plugin-ci phplint

      - name: Code checker
        run: moodle-plugin-ci codechecker

      - name: Validate plugin
        run: moodle-plugin-ci validate

      - name: PHPUnit
        run: moodle-plugin-ci phpunit
